version: '3.3'

services:
  db:
#    platform: linux/amd64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'points_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'


    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: